"use client";

import { useState } from "react";
import { PUMP_FUN_URL, PRIVATE_TABLE_RAKE_PERCENT, TOKEN_NAME, TOKEN_SYMBOL } from "@/lib/constants";

const FAQ_ITEMS = [
  {
    id: "wager-token",
    question: `What do I wager — SOL or ${TOKEN_SYMBOL}?`,
    answer: (
      <>
        <strong>{TOKEN_SYMBOL}</strong> only. Every buy-in, bet, and pot is
        denominated in our project token — the same coin launched on{" "}
        <a
          href={PUMP_FUN_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="text-amber-400 underline hover:text-amber-300"
        >
          pump.fun
        </a>
        . You are not posting SOL to the table; you are putting {TOKEN_NAME}{" "}
        chips into the pot. Hold the token in your wallet, join a room, and play.
      </>
    ),
  },
  {
    id: "flywheel",
    question: "What is the flywheel, and why does it matter?",
    answer: (
      <>
        <p className="mb-3">
          Most play-to-earn games fail because winners take tokens and
          immediately sell on the open market. That creates constant sell
          pressure and hurts everyone still holding.
        </p>
        <p className="mb-3">
          We designed around that. The loop looks like this:
        </p>
        <ol className="mb-3 list-decimal space-y-2 pl-5 text-slate-300">
          <li>
            Players wager <strong>{TOKEN_SYMBOL}</strong> at the tables (on-chain).
          </li>
          <li>
            Winners receive tokens from the pot — same asset, no forced
            conversion to SOL.
          </li>
          <li>
            Instead of dumping on the chart, winners can use our{" "}
            <strong>OTC redemption</strong> (see below).
          </li>
          <li>
            OTC is funded by <strong>pump.fun creator rewards</strong> earned
            from token activity.
          </li>
          <li>
            Every token bought back through OTC is <strong>burned</strong> —
            permanently removed from supply.
          </li>
        </ol>
        <p>
          Less winner dumping on the open market, more supply burned from real
          gameplay revenue. That is the flywheel: play → rewards → buyback →
          burn → tighter supply → healthier token for everyone still in the game.
        </p>
      </>
    ),
  },
  {
    id: "otc",
    question: "How does the OTC buyback work?",
    answer: (
      <>
        <p className="mb-3">
          <strong>OTC</strong> (over-the-counter) means you redeem winning{" "}
          {TOKEN_SYMBOL} directly with us — not through a public DEX order book.
        </p>
        <p className="mb-3">
          When you win a pot, you can either keep your tokens to re-buy into
          another table, or request an OTC redemption. We quote a fair rate and
          pay you from a pool funded by <strong>creator rewards</strong> on
          pump.fun (a share of trading fees that flow to the token creator).
        </p>
        <p className="mb-3">
          Tokens we buy back are <strong>burned</strong>. They do not sit in a
          treasury waiting to be sold later. They leave circulation permanently.
        </p>
        <p>
          This gives winners a real exit without adding sell pressure to the
          bonding curve or Raydium pool — which is exactly what we want to avoid.
        </p>
      </>
    ),
  },
  {
    id: "why-not-dump",
    question: `Why not just sell ${TOKEN_SYMBOL} on the market after I win?`,
    answer: (
      <>
        You can — nothing stops you from transferring tokens to a wallet and
        selling on pump.fun or a DEX. But every open-market sell pushes price
        down for the entire community, including players still seated at tables.
        <br />
        <br />
        OTC exists so winners have a <em>better default</em>: take liquidity from
        creator-reward-funded buybacks, get a clear quote, and let those tokens
        burn instead of hitting the chart. The more winners choose OTC over
        dumping, the stronger the flywheel becomes for long-term players and
        holders.
      </>
    ),
  },
  {
    id: "creator-rewards",
    question: "Where does the OTC money come from?",
    answer: (
      <>
        From <strong>pump.fun creator rewards</strong> — fees generated by
        trading activity on our token. As volume and attention grow, creator
        rewards accumulate. We allocate a portion of that revenue to fund OTC
        redemptions and burns, not to team wallets or market sells.
        <br />
        <br />
        Table volume drives token utility; token activity funds buybacks; buybacks
        reduce supply. That closes the loop.
      </>
    ),
  },
  {
    id: "on-chain",
    question: "Is poker actually on-chain?",
    answer: (
      <>
        <strong>Public cash games</strong> — yes for money: {TOKEN_SYMBOL} buy-ins sit in a
        program vault; joins, actions, and cash-outs are Solana transactions you can
        audit on Solscan. <strong>Demo and profile chip tables</strong> use server play
        chips (not escrow). See{" "}
        <a href="/fairness" className="text-violet-400 underline hover:text-violet-300">
          Fairness & verification
        </a>{" "}
        for the full breakdown.
      </>
    ),
  },
  {
    id: "provably-fair",
    question: "Is the game provably fair?",
    answer: (
      <>
        <p className="mb-2">
          <strong>Escrow and payouts</strong> — verifiable on-chain for cash games (open
          program, public account state, SPL vault).
        </p>
        <p className="mb-2">
          <strong>Card dealing</strong> — cash tables use on-chain VRF shuffle, deck
          commitments, and commit–reveal hole cards. We are waiting for an independent
          security audit; auditors can contact us on{" "}
          <a
            href="https://x.com/solanawsop"
            target="_blank"
            rel="noopener noreferrer"
            className="text-violet-400 underline hover:text-violet-300"
          >
            @solanawsop
          </a>
          .
        </p>
        <a href="/fairness" className="text-violet-400 underline hover:text-violet-300">
          Read what you can verify today →
        </a>
      </>
    ),
  },
  {
    id: "rewards-redeem",
    question: "Can I redeem reward points?",
    answer: (
      <>
        Yes — go to <strong>Profile → Rewards</strong> and pick a tier (table credits,
        featured seats, etc.). Points are deducted immediately; fulfillment is queued
        and shown as pending until applied. Points have no cash value until redeemed
        per program rules.
      </>
    ),
  },
  {
    id: "private",
    question: "How do private tables work?",
    answer: (
      <>
        Private SOL tables are coming soon — invite-only rooms with direct links,
        on-chain guest lists, and a {PRIVATE_TABLE_RAKE_PERCENT}% platform rake per pot.
        Public cash games use {TOKEN_SYMBOL} today.
      </>
    ),
  },
];

export default function FaqSection() {
  const [openId, setOpenId] = useState<string | null>("flywheel");

  return (
    <div>
      <div className="surface-card mb-6 rounded-2xl p-5 sm:p-6">
        <p className="section-label mb-4">The loop</p>
        <div className="flex flex-wrap items-center gap-2 text-xs text-zinc-400">
          {[
            `Wager ${TOKEN_SYMBOL}`,
            "Win",
            "OTC redeem",
            "Creator rewards",
            "Burn",
            "Less dumping",
          ].map((step, i) => (
            <span key={step} className="flex items-center gap-2">
              {i > 0 && <span className="text-[#e8c547]/50">→</span>}
              <span className="rounded-md border border-white/[0.06] bg-white/[0.03] px-2.5 py-1.5">
                {step}
              </span>
            </span>
          ))}
        </div>
      </div>

      <div className="space-y-2">
        {FAQ_ITEMS.map((item) => {
          const isOpen = openId === item.id;
          return (
            <div key={item.id} className="surface-card overflow-hidden rounded-xl">
              <button
                type="button"
                onClick={() => setOpenId(isOpen ? null : item.id)}
                className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left transition hover:bg-white/[0.02]"
              >
                <span className="text-sm font-medium text-zinc-200">
                  {item.question}
                </span>
                <span
                  className={`shrink-0 text-[#e8c547] transition-transform ${isOpen ? "rotate-45" : ""}`}
                >
                  +
                </span>
              </button>
              {isOpen && (
                <div className="border-t border-white/[0.06] px-5 py-4 text-sm leading-relaxed text-zinc-500">
                  {item.answer}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
